AWSTemplateFormatVersion: "2010-09-09"
Description: Elastic container registry
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: training-ecs-services
      Subnets:
      - Fn::ImportValue:
          ":SubnetAZ1Public"
      - Fn::ImportValue:
          ":SubnetAZ2Public"
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: 'true'
        - Key: access_logs.s3.bucket
          Value: !ImportValue BucketLoadBalancer